name = "WinterPack"
author = "Dylan"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcc0cb5c8a3abad0c5fb039db7b84ac0cc3b05660ece975b770214dc430d9600"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
